import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../styles/common.css";
import "../styles/layout.css";
import SideNav from "@/components/sidebars/sideNav";
import Providers from "@/wrappers/Providers";
import { Toaster } from "sonner";
import Data from "@/wrappers/Data";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <main className="layout-grid">
          <div className="pt-4 pb-4 z-10">
            <SideNav />
          </div>
          <section className="page-container">
            <Providers>
              <Data>{children}</Data>
            </Providers>
          </section>
          <div></div>
        </main>
      </body>
    </html>
  );
}
